spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

spring.datasource.url=${jdbc:postgresql://dpg-d8aoelmk1jcs7385df5g-a:5432/resumedb_f111}
spring.datasource.username=${resumedb_f111_user}
spring.datasource.password=${7Xu19kmqac3n89F1uix8u7PnfwSDUvhj}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


