spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

spring.datasource.url=${jdbc:postgresql://dpg-d8aoelmk1jcs7385df5g-a:5432/resumedb_f111}
spring.datasource.username=${resumedb_ddd1_user}
spring.datasource.password=${pgl440y5rLeoj19NLMjzQzFBQvbExGTy}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



