spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}

spring.datasource.url=${jdbc:postgresql://dpg-d83gpnd7vvec739ea6f0-a:5432/resume_db_rszv}
spring.datasource.username=${resume_db_rszv_user}
spring.datasource.password=${XHzvRgiWOyk29kc8JIILRxi7SfYzM2Fb}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


